require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "bin/bundle"
    - "db/schema.rb"
    - "lib/tasks/auto_annotate_models.rake"

Lint/RedundantCopDisableDirective:
  Enabled: false

Style/Documentation:
  Enabled: false
