databases:
  - name: my-tarot-api
    databaseName: my-tarot-api
    user: my-tarot-api

services:
  - type: web
    name: my-tarot-api
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-tarot-api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
